// define type of action here

const FETCH_SEARCH_IDS_REQUEST = "FETCH_SEARCH_IDS_REQUEST";
const FETCH_SEARCH_IDS_SUCCESS = "FETCH_SEARCH_IDS_SUCCESS";
const FETCH_SEARCH_IDS_FAILURE = "FETCH_SEARCH_IDS_FAILURE";
const FETCH_SEARCH_RESULTS_REQUEST = "FETCH_SEARCH_RESULTS_REQUEST";
const FETCH_SEARCH_RESULTS_SUCCESS = "FETCH_SEARCH_RESULTS_SUCCESS";
const FETCH_SEARCH_RESULTS_FAILURE = "FETCH_SEARCH_RESULTS_FAILURE";
const SET_SEARCH_COLUMN = "SET_SEARCH_COLUMN";
const SET_SEARCH_SETTINGS = "SET_SEARCH_SETTINGS";
const SET_FILTERS_ENABLE = "SET_FILTERS_ENABLE";
const SET_FILTERS = "SET_FILTERS";
const INCREMENT_OFFSET = "INCREMENT_OFFSET";
const UPDATE_TOTAL_COUNT = "UPDATE_TOTAL_COUNT";
const UPDATE_COURSE_TABLE = "UPDATE_COURSE_TABLE";
const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
const UPDATE_USER = "UPDATE_USER";
const SET_DISPLAY_TAGS = "SET_DISPLAY_TAGS";

export {
  FETCH_SEARCH_RESULTS_FAILURE,
  FETCH_SEARCH_RESULTS_SUCCESS,
  FETCH_SEARCH_RESULTS_REQUEST,
  FETCH_SEARCH_IDS_FAILURE,
  FETCH_SEARCH_IDS_REQUEST,
  FETCH_SEARCH_IDS_SUCCESS,
  SET_SEARCH_COLUMN,
  SET_SEARCH_SETTINGS,
  SET_FILTERS,
  INCREMENT_OFFSET,
  UPDATE_TOTAL_COUNT,
  SET_FILTERS_ENABLE,
  UPDATE_COURSE_TABLE,
  LOG_IN_SUCCESS,
  LOG_OUT_SUCCESS,
  UPDATE_USER,
  SET_DISPLAY_TAGS,
};
