// define type of action here

const FETCH_SEARCH_RESULTS_REQUEST="FETCH_SEARCH_RESULTS_REQUEST";
const FETCH_SEARCH_RESULTS_SUCCESS="FETCH_SEARCH_RESULTS_SUCCESS";
const FETCH_SEARCH_RESULTS_FAILURE="FETCH_SEARCH_RESULTS_FAILURE";
const SET_SEARCH_COLUMN="SET_SEARCH_COLUMN";

export {FETCH_SEARCH_RESULTS_FAILURE,FETCH_SEARCH_RESULTS_REQUEST,FETCH_SEARCH_RESULTS_SUCCESS,SET_SEARCH_COLUMN};