// define type of action here

const FETCH_SEARCH_IDS_REQUEST="FETCH_SEARCH_IDS_REQUEST";
const FETCH_SEARCH_IDS_SUCCESS="FETCH_SEARCH_IDS_SUCCESS";
const FETCH_SEARCH_IDS_FAILURE="FETCH_SEARCH_IDS_FAILURE";
const SET_SEARCH_COLUMN="SET_SEARCH_COLUMN";
const SET_SEARCH_SETTINGS="SET_SEARCH_SETTINGS"; 
const SET_FILTERS = "SET_FILTERS"

export {FETCH_SEARCH_IDS_FAILURE,FETCH_SEARCH_IDS_REQUEST,FETCH_SEARCH_IDS_SUCCESS,SET_SEARCH_COLUMN, SET_SEARCH_SETTINGS, SET_FILTERS};