name: E2E testing
on: [push]
jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: 🧪 Cypress run (Chrome)
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/e2e/*
          browser: chrome
          record: true
          build: yarn build
          start: node_modules/next/dist/bin/next start -p 3000
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.AZURE_API_ENDPOINT }}
          NEXT_PUBLIC_API_VERSION: "v1"
          NEXT_PUBLIC_ENV: "prod"
          AUTH0_SELF_API_AUDIENCE: ${{ secrets.SELF_API_AUDIENCE }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET_V2 }}
          AUTH0_BASE_URL: "http://localhost:3000"
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL_V2 }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID_V2 }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET_V2 }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_API_ENDPOINT: ${{ secrets.AZURE_API_ENDPOINT }}
          CYPRESS_API_VERSION: "v1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
